stages:
    - build

compiledist:
    stage: build
    script:
        - make redep
        - make -j $(cat /proc/cpuinfo | grep -c ^processor)
        - ./make_dist_version.sh
        - mv dist kriti-dist
        - rm -f kriti-dist.tar.gz
        - tar czf kriti-dist.tar.gz kriti-dist
        - ./upload_dist
